chore: Refactor MultiCode Expression ✨
graphql-python/graphql-core pull request #146
Opened 2021-11-05 11:31 UTC by yezz123

I just refactor some functions, mostly was simple like:
- Swap if & else branches.
- Merge Else If Into Elif.
- De Morgan Identity.

2021-11-05 13:49 UTC, Cito reviewed
Hi @yezz123, thanks for your contribution.

I'll go through your changes as time permits. One remark upfront: I try to keep the code very close to the original GraphQL.js code, so that the task of keeping the code bases in sync stays managable. That's why I often keep certain constructs or order of code blocks even if the code could be simplified or optimized.

2021-11-05 14:09 UTC, yezz123 commented
Hi @Cito 👋 

I got your idea about keeping the same one related to GraphQL.js code Yes, my changes are not something that touches the core, just a pythonic one related to refactoring some functions that need to function well and in a fast way.
I run the Local test all of the functions work smoothly ✨

2021-11-05 14:32 UTC, Cito requested changes

2021-11-05 14:32 UTC, Cito commented on src/graphql/language/block_string.py
> +    return all(c in [" ", "\t"] for c in s)
It's disputable what would be best for readability and performance here. Note that there are at least 5 alternatives that look good to me:
- `c in " \t"`
- `c == " " or c == "\t"`
- `c in [' ', '\t']`
- `c in (' ', '\t')`
- `c in {' ', '\t'}`

The first solution only works if you are sure that `c` is a single character. Note that creating a list, tuple or set has a certain cost.

Out of curiosity, I measured with `timeit` and found that in fact `set` is the fastest solution, even if you only have 2 options. I would have guessed that the effect would be only noticeable with more options. Note that you want to optimize both cases, that the condition is true and that it is false. With the set, you have always a constant time. The other solutions are slower when the condition is false, and become worse the more options you have.

2021-11-05 14:32 UTC, Cito commented on src/graphql/language/visitor.py
> +                    raise TypeError(f"Invalid AST node kind: {kind}.")
Yes, that's better.

2021-11-05 14:32 UTC, Cito commented on src/graphql/language/visitor.py
> +                    setattr(node, edit_key, edit_value)
These look good, too.

2021-11-05 14:32 UTC, Cito commented on src/graphql/language/block_string.py
> +    return all(c in [" ", "\t"] for c in s)
If we make that change, we should look if there are similar comparisons and change all of them.

2021-11-05 14:32 UTC, Cito commented on src/graphql/subscription/map_async_iterator.py
> +        result = self.callback(value)
Ok, maybe add a new line in front of this.

2021-11-05 14:32 UTC, Cito commented on src/graphql/utilities/strip_ignored_characters.py
> +    """
Why did you remove the rest of the docstring?

2021-11-05 14:32 UTC, Cito commented on src/graphql/utilities/strip_ignored_characters.py
> +            stripped_body += " "
This was a literal translation from GraphQL.js, but it's ok we can change that.

2021-11-05 14:32 UTC, Cito commented on src/graphql/validation/rules/lone_anonymous_operation.py
> +            isinstance(definition, OperationDefinitionNode)
This makes use of the fact that bool is an int subtype in Python and `1 == True`.

Yes, we can do that.

2021-11-05 14:32 UTC, Cito commented on src/graphql/validation/rules/single_field_subscriptions.py
> +        if node.operation != OperationType.SUBSCRIPTION:
You just want to avoid one level of indentation, right? Again, this was a literal translation from GraphQL.js, but ok, we can do that.

2021-11-05 14:32 UTC, Cito commented on src/graphql/validation/validation_context.py
> +            fragments = {
Yes, a dict comprehension is definitely better here.

2021-11-05 14:32 UTC, Cito commented on src/graphql/utilities/print_schema.py
> +    return not subscription_type or subscription_type.name == "Subscription"
Again, literally from GraphQL.js. But yes, let's do it a bit more elegantly here.

2021-11-07 01:05 UTC, yezz123 commented
Hey @Cito I just fix all that you recommend to add, I agree with you in all of the changes look good and logical, we don't need to break the logic of it also we need to keep it in a pythonic way 🚀✨.

You could run all the workflows before the merge

2021-11-07 12:49 UTC, Cito approved these changes
Thank you @yezz123

2021-11-07 12:56 UTC, yezz123 commented
Happy to contribute to one of the things that i use daily 🚀✨

2021-11-07 12:58 UTC, merged

2021-11-07 13:29 UTC, Cito commented on src/graphql/language/block_string.py
> +    return all(c in [" ", "\t"] for c in s)
For the records, I found that using a regex was even faster than all other solutions, and changed it in f917259a5ddc0b8a791a398cf2a459ec532f0736