Support middlewares for subscriptions
graphql-python/graphql-core pull request #221
Opened 2024-07-02 11:51 UTC by nrbnlulu

Fix #188

2024-07-05 07:57 UTC, nrbnlulu commented
@Cito can you aprove the workflows?

2024-07-05 19:46 UTC, Cito commented
Thanks, will review this tomorrow.

2024-07-07 18:02 UTC, Cito requested changes
Looks good to me, thank you.

Just minor stylistic changes for consistency, see suggestions.

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
> +                        resolve=lambda message, _: message,
```suggestion
                        resolve=lambda message, _info: message,
```

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
> +            test_type = GraphQLObjectType(
```suggestion

            test_type = GraphQLObjectType(
```

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
> +from graphql import subscribe
```suggestion
from graphql.execution import Middleware, MiddlewareManager, execute, subscribe
```

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
>  from graphql.execution import Middleware, MiddlewareManager, execute
```suggestion
```

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
> +            assert data == {"bar": "foo"}
```suggestion

            async def reverse_middleware(next_, *args, **kwargs):
                return next_(*args, **kwargs)[::-1]

            noop_type = GraphQLObjectType(
                "Noop",
                {"noop": GraphQLField(GraphQLString, resolve=lambda *_args: "noop")},
            )
            schema = GraphQLSchema(query=noop_type, subscription=test_type)

            subscription = subscribe(
                schema,
                parse("subscription { bar }"),
                middleware=MiddlewareManager(reverse_middleware),
            )
            assert inspect.isasyncgen(subscription)
            data = (await subscription.__anext__()).data
            assert data == {"bar": "rab"}
            data = (await subscription.__anext__()).data
            assert data == {"bar": "foo"}
```

2024-07-07 18:02 UTC, Cito commented on tests/execution/test_middleware.py
> +def _create_subscription_schema(tp: GraphQLObjectType) -> GraphQLSchema:
Since this is only used in one test, better move it there (see suggestion below).

2024-07-07 19:25 UTC, Cito requested changes
The dummy resolver can be removed.

2024-07-07 19:25 UTC, Cito commented on tests/execution/test_middleware.py
> +                {"noop": GraphQLField(GraphQLString, resolve=lambda *_args: "noop")},
```suggestion
                {"noop": GraphQLField(GraphQLString")},
```

2024-07-07 19:25 UTC, Cito commented on tests/execution/test_middleware.py
> +                {"noop": GraphQLField(GraphQLString, resolve=lambda *_args: "noop")},
This is not needed and should also solve the coverage issue.

2024-07-07 20:06 UTC, Cito approved these changes

2024-07-07 20:06 UTC, merged